---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull vipul2097/mini_dockerimage

    - name: running container
      shell: docker create -it vipul2097/mini_dockerimage